project:
  type: website
  output-dir: docs

website:
  title: "Statistics, plain and sample"
  site-url: "https://gjkerns.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gjkerns
      - icon: twitter
        href: https://twitter.com/gkerns
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

